//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsrSpeedrun
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public int Id { get; set; }
        public int DemandId { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Roomscount { get; set; }
        public Nullable<double> Area { get; set; }
    
        public virtual Demand Demand { get; set; }
    }
}
