//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creationOfOneToOneRelationsWtihPopUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CocosPackage
    {
        public int Id { get; set; }
        public int CocosId { get; set; }
        public int age { get; set; }
        public bool isFinished { get; set; }
    
        public virtual Coco Coco { get; set; }
    }
}
