//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convertor
{
    using System;
    using System.Collections.Generic;
    
    public partial class house
    {
        public int PlaceId { get; set; }
        public Nullable<int> TotalFloors { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public Nullable<int> TotalRooms { get; set; }
    
        public virtual place place { get; set; }
    }
}
